language: php

php:
    - 5.3
    - 5.4
    - 5.5

env:
  - SYMFONY_VERSION=2.2.*
  - SYMFONY_VERSION=2.3.*
  - SYMFONY_VERSION=dev-master

before_script:
  - composer require symfony/symfony:${SYMFONY_VERSION} --no-update
  - composer update --dry-run

# we are really only interested if the composer runs through or not
script: phpunit --version

notifications:
  email: "nbastien@prestaconcept.net"

matrix:
  allow_failures:
    - env: SYMFONY_VERSION=dev-master
